version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - servernet
    restart: always

  db:
    image: mysql/mysql-server:5.7
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
      - data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1250623585_Wly
    networks:
      - dbnet
    restart: always
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问

    
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - "80:80"
    restart: always
    

networks:
  servernet:
  dbnet:

volumes:
  data-storage:
  data-tmp:
  data-mysql:
